### ISSUE TITLE
No text formatting

### ISSUE THREAD

**Issue by moonwolf-github** [raelgc/scudcloud#126]
In Fedora (KDE), when someone uses text formatting (bold or italic) there is no effect  - when inspecting there are html tags, but message appears in plain text. Using Lato 2.0 font doesn't help.

**Comment by raelgc** [comment]
You need to install any fixed width font. In Ubuntu package, suggestion is the package with `mscorefonts`, because it has the Courier New font. See #39. 

For RPM, you need the `msttcore-fonts-installer` package. If not provided in default install, please, get it from http://mscorefonts2.sourceforge.net/
