### ISSUE TITLE
Compact message style incorrect show

### ISSUE THREAD

**Issue by frontiertsymbal** [raelgc/scudcloud#139]
The problem with the display of compact messages.
System - RFRemix Fedora 21 Cinnamon

![2015-06-11 10 08 30](https://cloud.githubusercontent.com/assets/9643428/8101706/5f1a4f46-1022-11e5-8b48-6505734120a6.png)

**Comment by raelgc** [comment]
Hi @frontiertsymbal, thanks for reporting this issue.

First and more important: where is this party from the picture? :D

Now about the compact incorrectly displayed: ScudCloud is basically just a webkit wrapper for Slack with some desktop interaction.

This issue sounds like you don't have Font Lato installed or old webkit package.

**Comment by TheTechmage** [comment]
I would just like to say that I'm seeing the exact same thing.  My version of webkit should be fairly up-to-date ish, since I updated my system a month or two ago. As far as font lato? I can't seem to find that font anywhere in the official Archlinux package repositories, nor the user repository. So I'm not sure how I could go about installing it. I've also tried changing the Lato font setting to no avail. :S I have noticed that the little [ stays the same size no matter how far I've zoomed in or out.

Arch packages:

```
$ pacman -Qs webkit
local/lib32-qt4 4.8.6-4
    A cross-platform application and UI framework (32-bit)
local/qtwebkit 2.3.4-1
    An open source web browser engine (Qt port)
local/surf 0.6-2
    A simple web browser based on WebKit/GTK+.
local/webkitgtk2 2.4.8-2
    GTK+ Web content engine library for GTK2
```

P.S. You mentioned that it's a webkit wrapper around slack. Does this mean that there is no easy way to get slack to log all messages to a directory so I can read them when I don't have a gui at my disposal? (just curious)

**Comment by raelgc** [comment]
@frostyfrog and @frontiertsymbal: You can get the font this way:
1. Download the .deb package file: http://packages.ubuntu.com/trusty/all/fonts-lato/download
2. Extract it.
3. Go to the extracted folder `usr/share/fonts/truetype/lato/`.
4. Install all fonts in there (usually in Gnome/KDE you can just right click and select `Install`).

@frostyfrog, about your question: indeed, the program intercepts direct messages and mentions to get them displayed as system notifications (you can see the method called [here](https://github.com/raelgc/scudcloud/blob/master/scudcloud-1.0/lib/wrapper.py#L147)). So, maybe you can write some code to save them in a folder.

**Comment by TheTechmage** [comment]
Thank you @raelgc for helping out with that. I am sad to report, however, that the stray [ is still present after installing the lato font and rebuilding the font cache (with `fc-cache -f`) I decided to updat my webkit package to `qtwebkit-2.3.4-2-x86_64`, which didn't help at all :disappointed: 

If you have any other ideas for me to try, I'm all ears.

**Comment by raelgc** [comment]
@frostyfrog Is there any `webkitgtk3` package?

**Comment by TheTechmage** [comment]
I have just installed (`webkitgtk-2.4.9-1-x86_64`) for gtk3 support. Unless a reboot is necessary (I'm a bit doubtful it is though, due to the way linux works), it didn't help at all, @raelgc.

**Comment by raelgc** [comment]
@frostyfrog still facing this issue?

**Comment by TheTechmage** [comment]
I'll have to check this on Wednesday when I'm in the office again.
