### ISSUE TITLE
How can I change the order of my slack chats?

### ISSUE THREAD

**Issue by azat-io** [raelgc/scudcloud#201]
Hello!

Could you tell me please:
1. I need to reorder my slack chats. How can I do it?
2. How can I turn off the option to increase the size of the selected chat?
3. How can I hide white program menu? It looks not good (file, edit, view, help).

**Comment by raelgc** [comment]
Hi @azat-io,
1. The chat saved as default one is the last used. Not sure if it'll be open as first (probably not). Because ScudCloud will persist the Slack session when you close it. 

If this not works, maybe, you should delete your config (`/.config/scudcloud`) and then login in the team you want as first.
1. This is defined in `/opt/scudcloud/resources/leftpane.html`. But, if you're using Ubuntu (or derivative), you should use `dpkg-divert` like described [here](http://unix.stackexchange.com/questions/107704/debian-keep-custom-changes-in-initscript) to preserve your changes throw updates.
2. This is not a ScudCloud problem. I'm not being rude: ScudCloud just uses the QT library to build the app menu. You should search for fix QT app menu appearance in your distro.

**Comment by raelgc** [comment]
@azat-io I'm thinking in a semi-solution for this: add sorting capability using drag & drop support in the left pane. It'll no persist the order, but... And probably it'll require more RAM usage, as this will rely on jQuery UI.

**Comment by raelgc** [comment]
I'll follow the KISS approach to fix this: the order of registered teams will be the order of displayed teams. If you need a different order, remove config and add again.
