### ISSUE TITLE
Chrome fonts changed

### ISSUE THREAD

**Issue by sanyocc** [raelgc/scudcloud#257]
I don't know if it's actually a bug but after installing scudcloud the default Chrome font changed to more look-alike Microsoft one (as seen on IE10). It's totally ok for me as this font is smoother and nicer than default one, but I guess this should be reported anyway.

Ubuntu 15.04 x64
Chrome 45 x64

**Comment by raelgc** [comment]
It's because ScudCloud install the `ttf-mscorefonts-installer` package, which contains some fonts that are used by Slack and are default to Chrome too.

As they were missing by default, Chrome was using the fonts existing in Ubuntu.

I.e., it's not a bug.

In case someone wants to revert this, just uninstall the package `ttf-mscorefonts-installer`.
