### ISSUE TITLE
Notice: Submitted Scudcloud SRPM for inclusion in Fedora

### ISSUE THREAD

**Issue by stieg** [raelgc/scudcloud#267]
Just wanted to send you all a heads up that I have created a package for scudcloud for inclusion in the Fedora ecosystem.  Info below...

Ticket: https://bugzilla.redhat.com/show_bug.cgi?id=1273693
Spef file:http://triplehelix.org/~stieg/specs/scudcloud.spec
SRPM: http://triplehelix.org/~stieg/srpms/scudcloud-1.0.84-1.fc23.src.rpm

**Comment by hogarth-sv** [comment]
Note that working on issue #85 will help with that as right now this doesn't really follow the [python packaging guidelines](https://fedoraproject.org/wiki/Packaging:Python) since the missing setup.py prevents use of the %py_build and %py_install macros ... which means things like pyc files won't be generated and installed.

**Comment by stieg** [comment]
Good to know.  Will hack on it.

**Comment by raelgc** [comment]
@hogarthj #85 is fixed now :)

**Comment by raelgc** [comment]
Thanks to @stieg big work!

**Comment by selurvedu** [comment]
@raelgc, https://pkgs.org/search/scudcloud
It is up-to-date and fully usable, so this issue can be closed now.

**Comment by raelgc** [comment]
Thank you @selurvedu!
