### ISSUE TITLE
My links are not previewed anymore

### ISSUE THREAD

**Issue by tmortagne** [raelgc/scudcloud#282]
Since 1.0.86 or 87 (not fully sure and it's still true in 1.0.89) my links are not previewed to me and others when sent from scudcloud but I can see a preview of links sent by other people or links I send from Firefox.

System:
- Ubuntu 15.10
- Scudcloud 1.0.89

**Comment by raelgc** [comment]
Hi @tmortagne and thanks for reporting this issue.

We do not have directly control over this, but I know one simple config that we changed and maybe can be related.

In my side, I can see preview of some links, not all, but anyway, the same behaviour when working from Firefox.

In order to investigate this, can you post a sample of the links posted from ScudCloud that not works (no preview) and sample of links posted from Firefox that works?

**Comment by tmortagne** [comment]
The following link works (is previewed) for me when posted from FF 41.0.2 and not from scudcloud 1.0.89:
https://scontent-cdg2-1.xx.fbcdn.net/hphotos-xtp1/v/t1.0-9/12187873_892428667478144_8477459624624538379_n.jpg?oh=3d3c1c4b6d928855375eb830fc325549&oe=56B13CE5

**Comment by raelgc** [comment]
Right, thanks @tmortagne 

Now, can you test the following?

First, exit ScudCloud.

Then, as `sudo`, edit the following file: `/opt/scudcloud/lib/resources.py` and change this line:

``` python
    APP_NAME = "ScudCloud Slack_SSB"
```

to this:

``` python
    APP_NAME = "ScudCloud"
```

Save and close the file.

Now try to post the link again.

**Comment by tmortagne** [comment]
Just modified the APP_NAME and that worked well :)

**Comment by raelgc** [comment]
@tmortagne So, this is more one behaviour affected by the APP_NAME.

The name including `Slack_SSB` will identifies ScudCloud as a desktop client (the same used in OSX, I think), and while the link preview will work fine, you'll notice one less desirable:

While clicking in any external link, it'll be opened using a Slack redirect server... so, if you right click and copy the link, you'll not copy the exact link.

**Comment by tmortagne** [comment]
Ok I see.
