### ISSUE TITLE
Cannot log into teams

### ISSUE THREAD

**Issue by paoloantinori** [raelgc/scudcloud#296]
It might be related to the presence of multiple teams, since I have never had the problem before yesterday when I have added a new one.

After a click on  a team I am already logged in with, the loading screen never goes away.

I have tried starting with `--debug DEBUG` but it didn't include anything relevant.

Platform is Fedora23

**Comment by lpetrica** [comment]
Same here, on Ubuntu 14.04. Working fine with multiple teams up until today when I changed the password of one team and tried to log back in.

Running with debug shows nothing of significance. While trying to connect, a python process takes about 40% of my CPU time.

**Comment by raelgc** [comment]
Please, upgrade.

**Comment by paoloantinori** [comment]
This fixes it, thank you. (It's not yet in `.rpm` though.)

**Comment by emyrTomos** [comment]
I have been removed from my old employers slack rooms - I am now trying to get into my new employers slack rooms but the preferences menu is disabled. I can't get in and click around because there is nowhere for me to click around to. How can I remove my old employers and allow scudcloud to initiate a new connection? I have tried removing and reinstalling - this was from the apt-get packages for ubuntu 15.10, if I need newer packages could you point me at them? 
tx
em

**Comment by raelgc** [comment]
Hi @emyrTomos, how are you?

Yes you can, but it's a manual solution: after close ScudCloud, you have to remove ScudCloud config file at `~/.config/scudcloud/scudcloud.cfg`.

**Comment by emyrTomos** [comment]
cool thanks rael all done :-)

**Comment by raelgc** [comment]
You're welcome, @emyrTomos, feel free to raise any questions/issues :)
