### ISSUE TITLE
Option to use Ctrl+Enter for sending message

### ISSUE THREAD

**Issue by maximw** [raelgc/scudcloud#306]
Please, add option to set Ctrl-Enter shortcut for sending message and Enter for inserting new line.
It's a common option for messengers. And it's a quite difficult to use ScudCloud in other way.

**Comment by raelgc** [comment]
Hi @maximw and thank you for reporting this issue.

Really sorry for this, but I should say the we're not willed to implement this kind of feature. The reason is because ScudCloud is just a simple wrapper for Slack, and our main guideline is not interfere in how Slack itself works.

But, if you want this behavior, you should raise an issue on Slack itself, pressing <kbd>F1</kbd> and then clicking on `Send us a help request`.

Again, sorry for the inconvenience!
