### ISSUE TITLE
Channel list not scrollable

### ISSUE THREAD

**Issue by edmundcraske** [raelgc/scudcloud#309]
When clicking 'Channels' in the menu on the left, it opens a window showing all channels on the current team. Although ScudCloud has a scrollbar, it doesn't seem to allow scrolling to view the whole channel list. See screenshot.
![scudcloud-channel-list-issue](https://cloud.githubusercontent.com/assets/1419739/11623950/496fbbf8-9cc8-11e5-8db8-428d3327b53e.png)

**Comment by edmundcraske** [comment]
Not sure if this is specific to my environment - I'm running Linux Mint Cinnamon.

**Comment by raelgc** [comment]
Hi @edmundcraske, thanks for reporting this issue.

I checked here: same on Unity.

In Firefox, a CSS scrollbar is displayed.

Probably it's related to #280 and #291. I'll investigate it.

**Comment by raelgc** [comment]
@edmundcraske Fixed and published in Ubuntu PPAs.

**Comment by ahbril** [comment]
I think it still not works properly. For me, it hurst when I look at the team members list. I can see a scroll bar now, but for some reason still some members are left out at the end. So I can scroll down to the bottom, and some people are simply missing.

As before, the only way to see them is to resize the entire window, which in our case means using alt-click to move the window because the window needs to be a lot larger than my screen is ...

**Comment by raelgc** [comment]
@edmundcraske If it's properly fixed, please, re-open it and we'll fix it :)

**Comment by ghost** [comment]
Don't know what happened, but I didn't see some of the people I knew should be in the direct messages list. Then when I re-tried it, just to double-check, they were present. Not sure what caused it, but the scroll bar seems to work anyway. Hence, pls ignore my remark (the one I removed).

**Comment by edmundcraske** [comment]
Seems to work for me now, thanks! :)

**Comment by edmundcraske** [comment]
And nice work on fixing it so quickly too! :+1:
