### ISSUE TITLE
Scudcloud sets the volume to 100%, when playing sound

### ISSUE THREAD

**Issue by white-gecko** [raelgc/scudcloud#31]
Scudcloud seams to set the volume to 100%, when playing the notification sound. I can reproduce it by setting the volume to some silent value, clicking on “Send test notification” in the preferences. The first one is on normal volume, clicking “Send test notification” a second time will play the notification on 100% volume.
I'd expect the notification sound to always be played at the system set volume.

**Comment by raelgc** [comment]
@white-gecko Which distro, version and DE are you using? To be honest, there is no single line dedicated to sound in ScudCloud.

The only thing that come to my mind is: I'm just enabling the webkit plugins. Maybe they're changing the volume.

Can you test this: open `/opt/scudcloud/lib/wrapper.py`, comment/disable this line (using `#` char):

```
QWebSettings.globalSettings().setAttribute(QWebSettings.PluginsEnabled, True)
```

Restart ScudCloud and check if this stop to happen?

**Comment by white-gecko** [comment]
Thank you for your reply. But this doesn't seam to fix the problem. I still see the same behavior.

**Comment by raelgc** [comment]
@white-gecko: the sound part is produce by Slack HTML, which runs under QtWebkit.

We can try to isolate this issue (maybe update some component), but you need to tell me which distro, version, desktop environment and QtWebkit you're using.

**Comment by white-gecko** [comment]
Ah sorry, I forgot that in the last post: Its Debian/jessie with Gnome 3.14.1 and [libqtwebkit4 2.3.4](https://packages.debian.org/jessie/libqtwebkit4)

**Comment by raelgc** [comment]
@white-gecko Still an issue?

**Comment by white-gecko** [comment]
Yes the issue still exists. I'm currently using "mute all sounds" as workaround.

**Comment by raelgc** [comment]
@white-gecko Can you, as `root`, edit `/opt/scudcloud/lib/wrapper.py` and disable the following line line below? (Usually at line `26`):

```
# QWebSettings.globalSettings().setAttribute(QWebSettings.PluginsEnabled, True)
```

Just to check if it's a plugin messing if your sound.

**Comment by white-gecko** [comment]
Still the same behavior, but I guess I'm not on the current develop branch, since the line you are giving is not at line 26 but at line 17.

**Comment by white-gecko** [comment]
I've tried it on the current master branch and still the same issue with and without plugins.

**Comment by NyanSten** [comment]
This is not caused by ScudCloud but by very stupid default settings of PulseAudio. Setting `flat-volumes = no` in `/etc/pulse/daemon.conf` and restarting PulseAudio should fix it.

**Comment by white-gecko** [comment]
Thanks, that works and fixes the problem.

**Comment by white-gecko** [comment]
trivia, this also fixes some issue with banshee :-)

**Comment by raelgc** [comment]
@white-gecko I'm glad this worked. Thanks @StenSoft for post this solution!

**Comment by NyanSten** [comment]
@white-gecko Yes, ScudCloud was not the only one affected, on my computer it affected also Skype and KNotify. That's why I started digging into PulseAudio on this.

**Comment by sruggier** [comment]
I think it's notable that Skype and KNotify are also based on Qt, so rather than blaming pulseaudio, I think it's more likely that this is a bug or configuration issue in Qt. If it really is Qt's fault, it may make sense to re-open this issue.

**Comment by raelgc** [comment]
Hi @sruggier and thank you for adding more info to this issue.

But the fact is ScudCloud has zero lines dedicated to sound. The Slack sounds are played by the web-browser component, based on webkit.

And, like stated above, configuring pulseaudio you can fix this.

**Comment by sruggier** [comment]
Alas, changing that pulseaudio setting didn't resolve this for me. I found the alternative behaviour was worse, so I was forced to re-enable `flat-volumes`. Sadly, I didn't take a note as to why, and now I don't remember the exact reason. Given that it motivated me to turn flat-volumes back on, it probably involved my ears suddenly getting blown out.

**Comment by raelgc** [comment]
By the way, which distro, version and desktop environment are you using, @sruggier?

And just to add something about the weird sound behavior (which, of course, we'd love to fix if find the root cause): when I tried Ubuntu 15.10, ScudCloud **sound** was working, then after some update, it stopped to work and I was not able to get it working again. For additional reasons, I got back to 14.04.

Like you said, it's something probably related to Qt

**Comment by sruggier** [comment]
Right now I'm on Linux Mint Debian edition, based on Jessie, using a Cinnamon session. It's pretty similar to what the reporter of the issue is using.

**Comment by CubeTheThird** [comment]
I am also experiencing this issue, using Arch Linux. The setting for flat-volume was already set to no, so that's not the cause (for me). I strongly suspect (at least in my case) that this is a bug in one of the underlying libraries or applications, as when testing the notification sounds, they will sometimes make a popping noise, or play a sound, but rarely do anything.

**Comment by sruggier** [comment]
By the way, I disabled flat-volumes again, which had the immediate side-effect of making ScudCloud very quiet, for some reason. I think that was what prompted me to go back last time. This time, though, I managed to bring the mixing controls back into a good place, and I've been using it as a workaround ever since.

**Comment by raelgc** [comment]
@sruggier Thank you for sharing the workaround!
