### ISSUE TITLE
Missing depedency on Ubuntu

### ISSUE THREAD

**Issue by chrisvdb** [raelgc/scudcloud#342]
python3-notify2 seems to be missing from dependency list of Ubuntu package.

**Comment by raelgc** [comment]
Hi @chrisvdb and thanks for reporting this!

Probably it'll fit in the `Suggests` session, as ScudCloud includes a pure python implementation too (and it'll use this if `python3-notify2` is not installed.

**Comment by chrisvdb** [comment]
Interesting... after installing the latest version yesterday it failed to start complaining about missing notify2. I fixed it by manually installing python3-notify2. So, it looks like, for me at least, the fallback is not working properly. On an aside, since installing 1.2 and the python3-notify2 the icon in the traybar looks/behaves much better than before.

$ apt-cache show scudcloud 
Package: scudcloud
Priority: optional
Section: python
Installed-Size: 338
Maintainer: Rael Gugelmin Cunha rael.gc@gmail.com
Architecture: all
Version: 1.2-0
Recommends: sni-qt, fonts-lato, gir1.2-unity-5.0, libqtwebkit-qupzillaplugins, python3-hunspell, python3-gi, ttf-mscorefonts-installer
Depends: libqtwebkit4 (>= 2.3.2), python3 (>= 3.4), python3-setuptools, python3-dbus, python3-pyqt4, xdg-utils
Filename: pool/main/s/scudcloud/scudcloud_1.2-0_all.deb
Size: 37298
MD5sum: 7ed469a69128ba997e50943bcbf49912
SHA1: 6dde237b79dfcf8296b0b3246ee2fa27e8f98ea8
SHA256: 69b65cdd614393db4738fab1aedcb07e638034b8bbd6efa9c741dd827c7bb0e8
Description-en: ScudCloud is a non official desktop client for Slack
 ScudCloud is a non official desktop client for Slack.
 Slack (http://slack.com) is a platform for team communication.
Description-md5: 186d8ab2e71fece379e71251cb5519f0

**Comment by mjosifek** [comment]
I can confirm that scudcloud 1.2 doesn't start without notify2. I had to install it manually as well. (scudcloud 1.2 manually installed on CentOS 7)

**Comment by raelgc** [comment]
Good to know that icon in tray is better now!

Really interesting x2, because I don't have this package (`python3-notify2`) installed. Anyway, I don't use ScudCloud minized to tray (to notice an improvement in the icon), I just implemented this due popular request.

I'm guessing Unity has installed any other related package which fixes it. Which DE are you using?

Anyway, I can see this package is available for Ubuntu since `12.04` and for Debian since `wheezy`.

So, probably we can include as `Depends` to avoid this issue you've faced (and with a `+1` from @mjosifek).

**Comment by chrisvdb** [comment]
I use Kubuntu 15.10 with backported KDE packages. I agree that it's probably safe to include it in the depends (and it's small as well).
