### ISSUE TITLE
Window is not hinted with the "urgency" flag

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [raelgc/scudcloud#401]
I'm using the notion window manager, which relies on X clients setting the ["urgency" flag in the window HINT](https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html#URGENCY)s to manage notifications. Most applications do this to get the user attention when there is some events. It would be good if scudcloud does it too.

**Comment by raelgc** [comment]
Hi @leandro-lucarella-sociomantic and thanks for raising this issue!

Currently we've disabled this, because in some DEs, like Cinnamon, the window will steal focus.

Basically, to enable this in other DEs, we'll need to create a proper way to check which DE is running.

The code to set window to urgent (and removed) is:

``` python
QApplication.alert(self.parent)
```

**Comment by leandro-lucarella-sociomantic** [comment]
What about adding some (command-line) option to enable it?

**Comment by raelgc** [comment]
Sounds like an interesting idea!
