### ISSUE TITLE
Offical Slack client

### ISSUE THREAD

**Issue by mhalano** [raelgc/scudcloud#420]
I think this project could deprecated now. The reason for that is tehere an official client for Slack. Deprecate some project isn't bad it all. Means the world is evolving. In this case means Slack company noticed Linux user and want them be happy.

What you think guys?

**Comment by stieg** [comment]
I would say I respectfully disagree.  Reason is that the Slack group does not provide their code as OSS.  Because of that if their code should break for any reason, we are left without recourse.  As a result we would be completely at their mercy.  And that is not good at all.  While this project has its challenges since there is no official API for Slack, folks can still contribute to it and use it and make it work on their systems.  Hence why it should carry on until such time that the Slack team fully open's their client code to the community.  Then and only then would it make sense to re-evaluate position; or unless all the devs left the project.

**Comment by raelgc** [comment]
Hi @mhalano, and thanks for open this discussion.

We talked a bit about this when the beta client was released (#221).

But, basically: all the Slack clients are, until now, simple wrappers around the web version.

While the official client works well, ScudCloud has few advantage over it:
- less memory usage
- support to more distros then Ubuntu and Fedora
- better integration with Ubuntu Unity
- open source (while you can uncompile the official client and take a look in the copyrighted code) 

The project got several improvements in the latest months, and it's pretty stable now, requiring less support from the team.

So, as @stieg pointed, while the team is motivated to keep this project moving forward, we're still in the business.
