### ISSUE TITLE
Spell checking of multiple languages

### ISSUE THREAD

**Issue by Exoth** [raelgc/scudcloud#45]
I regularly type in both English and Russian languages.
So when I have both hunspell-en-us and hunspell-ru packages installed, English language is spellchecked, but all Russian words are considered wrong.
Is there any way to spellcheck in multiple languages at the same time?

**Comment by raelgc** [comment]
One possible workaround is to try merge both dictionaries in a new one like described here: http://superuser.com/questions/693283/use-multiple-languages-at-once-for-the-dictionary

Then placed it where hunspell dictionaries are installed.

**Comment by Exoth** [comment]
I'll try it out, thanks.

**Comment by raelgc** [comment]
Closing by inactivity. Please, re-open if required.

**Comment by burabure** [comment]
this is very annoying. Isn't there a way to select the dict like in a web browser (right click...), if now Is there a way to turn spell checking off altogether?

**Comment by raelgc** [comment]
Hi @burabure. I can realize how this is frustrating.

The problem is: part of the spell checking (marking words in red) is provided by C code, from QupZilla webkitplugins project. I'm not willed to change this code (if you find someone that can help, I'll be glad).

The other section, the one to suggest changes, it belongs to ScudCloud, and I can improve it, but it'll be really weird if we can change the suggestions, but not the red mark.

You can disable the red marks just uninstalling the `libqtwebkit-qupzillaplugins` package.

Sorry for the inconvenience.

**Comment by Grief** [comment]
@raelgc I guess I have the same question which @burabure has. If I have several dictionaries installed, how to choose which to use?
