### ISSUE TITLE
Missing tray icon when minimised

### ISSUE THREAD

**Issue by brendan-pike** [raelgc/scudcloud#524]
## ScudCloud Version

Paste the output for `scudcloud --version` below:
``
scudcloud --version
ScudCloud 1.40
Python 3.5.2+
Qt 5.6.1
PyQt 5.7
SIP 4.18.1

## Distro and Desktop info

  - Distribution:
  - Version/Release:
  - Desktop environment:

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.10
Release:	16.10
Codename:	yakkety

Desktop:  Cinnamon       3.2.8-201702

## Expected behavior

When scudcloud is minimised an icon should be shown in the panel (I have the 'close to tray' option selected'

## Actual behavior

Missing icon and no way to show scudcloud expect to use the main system menu

## Steps to reproduce
 1. Install Cinnamon desktop on Ubuntu 
 2. use scudcloud
 3. minimise

**Comment by ghost** [comment]
I have the same issue while using Manjaro with Cinnamon desktop.

$ scudcloud --version
```
ScudCloud 1.41
Python 3.6.0
Qt 5.8.0
PyQt 5.8
SIP 4.19.1
```
$ lsb_release -a
```
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	17.0
Codename:	Gellivara
```

$ cinnamon --version
```
Cinnamon 3.2.8
```

**Comment by wpoely86** [comment]
Same for me with 1.39 on Fedora 25 with wayland. It's there but without a visible icon (I can click on it). In the logs I see:
```
 QSystemTrayIcon::setVisible: No Icon set
```

**Comment by ben-cohen** [comment]
I have the same problem on Mint Cinnamon 17, and as @wpoely86 said a blank square that you can click on appears in the tray.

In Systray.__init__(), if I print out the QtGui.QIcon.themeName() I get an empty string.  If I then call QtGui.QIcon.setThemeName('hicolor') then the correct icon appears in the tray (though that won't be the correct fix!)

This is to do with Qt5 no longer inferring the theme for other Linux desktops (except GNOME and KDE).  See http://www.linux.org/threads/qt5-based-kde-applications-dont-appear-correctly-in-alternative-wms.8775/ for more details - perhaps users need to use qt5ct or qt5-styleplugins.  (Hopefully this will get fixed by distros eventually.)

**Comment by raelgc** [comment]
@ben-cohen thanks for sharing this info.

Maybe we can, as a workaround for now, use `QtGui.QIcon.setThemeName('hicolor')` when `QtGui.QIcon.themeName()` is empty.

Do you mind to create a PR with that?

**Comment by wpoely86** [comment]
Installing `qt5-styleplugins` did bring the icon back for me.

**Comment by raelgc** [comment]
Thank you @ben-cohen for the fix when we cannot detect a theme, and for @wpoely86 to mention this other package. I've published a new version with both fixes.
