### ISSUE TITLE
Latest release seems to deadlock/hang

### ISSUE THREAD

**Issue by shevek** [raelgc/scudcloud#542]
## ScudCloud Version

Paste the output for `scudcloud --version` below:
`ScudCloud 1.50
Python 3.5.2
Qt 5.5.1
PyQt 5.5.1
SIP 4.17
`

## Distro and Desktop info

  - Distribution:
  - Version/Release:
  - Desktop environment:
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

XFCE/XFWM.

## Expected behavior
scudcloud works

## Actual behavior
system renders title bar, but rest of window doesn't evn render. Sometimes crashes, sends apport bugs to launchpad
no cpu is being used, assume deadlock or waiting for http or something but it's all hung up, and (yay python) there's no debugger or remote process introspection or anything (yay python)

## Steps to reproduce
 1. open scudcloud with 9 or 10 teams logged in
 2. (usually) crash
 3. sometimes wait a bit then crash
 4. sometimes if you wait long enough it unhangs, sometimes it crashes and goes via apport
 5. version 1.48 didn't do this quite as much

**Comment by raelgc** [comment]
Hi @shevek and thanks for reporting this issue.

If you start ScudCloud from the command line, is there any stack?

If I correctly remember, in apport there is a section with some stack trace.

This version is using Qt5 instead of Qt4. While it improved the HTML container a lot (so I was able to remove a lot of workarounds for JS/CSS), probably we'll face new bugs to fix.

**Comment by shevek** [comment]
I noted a couple of stacks in #544 but I'm not sure if they're related.

**Comment by shevek** [comment]
P.S. if there are any active debug commands I can run when it's just eating up CPU, or idling and sitting there, let me know. Naturally, I'm a Java guy so I'm used to having full online instrumentation in the VM, so every time I get put on a python job, I use more bad language than is proper because I've no idea what's going on.

**Comment by dburm** [comment]
The same issue for Ubuntu Trusty/Mint 17. Doesn't depend on number of joined teams. 
Command line output on Trusty:
```
$ scudcloud 
Trying to construct an instance of an invalid type, type id: 67129088
```
Vesions:
```
$ scudcloud --version
ScudCloud 1.50
Python 3.4.3
Qt 5.2.1
PyQt 5.2.1
SIP 4.15.5
```
```
$ uname -a
Linux user.home.local 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by shahzaibmuneeb** [comment]
Same issue as dburm:

"Trying to construct an instance of an invalid type, type id: 67129088"

ScudCloud 1.50
Python 3.4.3
Qt 5.2.1
PyQt 5.2.1
SIP 4.15.5

**Comment by dburm** [comment]
It seems to be related to some external components. I've rebuilt previous versions (1.48 and 1.47) and downgraded current one - they doesn't work as well with the same symptom

**Comment by tinder-nsoracco** [comment]
fwiw 1.50 on Fedora 25 works fine.

**Comment by vectorsigma** [comment]
I compiled 1.50 for fedora 25 and it worked fine.  the cpu usage spikes in channels with urls.  that might be new, but it might not be.

**Comment by mocrel** [comment]
I wonder if my issue could be related to this. I use scudcloud with two teams. One of them works fine but the other one freezes on startup, i.e. when I click on the team's icon. It shows the welcome message (from "your friends at slack") but the screen is frozen. The progress ring does not spin. No channel names are shown. 

This started a couple of days ago. Could it be due to version 1.50? 

It may be important that the problematic team uses plug-ins, but the working one does not. How can I disable plug-ins when I start scudcloud in order to test if that has any effect? 

$ scudcloud --version
ScudCloud 1.50
Python 3.4.3
Qt 5.2.1
PyQt 5.2.1
SIP 4.15.5

$ uname -a
Linux carbon 3.13.0-112-generic #159-Ubuntu SMP Fri Mar 3 15:27:22 UTC 2017 i686 i686 i686 GNU/Linux

$ python3 -c "import ssl; print(ssl.OPENSSL_VERSION)"
OpenSSL 1.0.1f 6 Jan 2014

**Comment by raelgc** [comment]
@mocrel Hm, maybe. Which kind of plugins? Do you have a link?

**Comment by mocrel** [comment]
The problematic team uses the following four plugins:

Google drive
Google calendar
Email
to-do bot: https://www.todobot.io/slack/

However, in my own account I only use the Google drive plugin and I do this in both the problematic and the working team. So it may not be related to plugins after all. I only mentioned this as I had seen posts from 2015 on scudcloud freezing and it was recommended to try with plugins disabled (via the option --no_plugins=True, but it doesn't seem to be available anymore).

**Comment by raelgc** [comment]
The options to disable web plugins was removed because now all web-browser plugins are disabled.

Is the problematic account using Google authentication?

**Comment by mocrel** [comment]
No, none of the accounts uses Google authentication.

**Comment by mocrel** [comment]
My issue is actually the same as #551.

**Comment by raelgc** [comment]
This should be fixed now (I've made several small improvements). If you're still facing this issue, please re-open.

**Comment by dburm** [comment]
1.56 works fine, at least at Trusty. Thanx a lot!
Can't verify for Mint 17.
