### ISSUE TITLE
Broken UI overflow over application edges

### ISSUE THREAD

**Issue by rask** [raelgc/scudcloud#574]
Recently when opening ScudCloud, I've been having trouble with the Slack UI loading properly.

The issue manifests as the sidebar gone missing and the text input being pushed under the lower edge of the application window.

Window resizing does not fix it. Randomly reloading the window fixes it. Randomly closing and reopening ScudCloud fixes it.

I think the issue has something to do with the application web view container receiving a malformed height value, which pushes the web view contents under the edges of the application window.

This has been happening on two separate Ubuntu machines now. One instance has a single team tied to it, the second one has two. The team switcher pane operates normally.

## ScudCloud Version

`1.48`

## Distro and Desktop info

  - Distribution: Ubuntu
  - Version/Release: 14.04 (packages upgraded)
  - Desktop environment: Stock Unity

## Expected behavior

ScudCloud displays Slack main view and sidebar properly.

## Actual behavior

Somehow the Slack contents are pushed either waaay higher or waaay lower below the edges of the application window, rendering the app unusable.

## Steps to reproduce

Not certain.

**Comment by raelgc** [comment]
Hi @rask. 

This is because Slack calculates the position of some elements (like the text input) during its loading.

Sometimes I face this during a slow connection. Sometimes, when Slack itself update it's CSS/JS (last time, the message input got broken for 2 days, then they updated).

Scudcloud itself has zero code for positioning, except the position of the teams left bar.

**Comment by rask** [comment]
I see. I guess I'll try and see whether network connections or similar is to blame, I've been having some connection issues lately with other software. Thanks!
